"""add phase two commerce catalog

Revision ID: b22992da0be4
Revises: c0c434e814f6
Create Date: 2026-09-04 22:22:02.779342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22992da0be4'
down_revision = 'c0c434e814f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_product')
    )
    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_wishlist_product')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('specs', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('delivery_estimate', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seller', sa.String(length=160), nullable=False))
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image_urls', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('views')
        batch_op.drop_column('image_urls')
        batch_op.drop_column('features')
        batch_op.drop_column('seller')
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('delivery_estimate')
        batch_op.drop_column('stock')
        batch_op.drop_column('specs')
        batch_op.drop_column('discount')
        batch_op.drop_column('mrp')
        batch_op.drop_column('title')

    op.drop_table('wishlist_item')
    op.drop_table('cart_item')
    op.drop_table('cart')
    # ### end Alembic commands ###
