"""add product image galleries

Revision ID: b79c1cba3bda
Revises: 4c527f231160
Create Date: 2026-09-04 23:23:50.912262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79c1cba3bda'
down_revision = '4c527f231160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_image', sa.String(length=500), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('images')
        batch_op.drop_column('primary_image')

    # ### end Alembic commands ###
